// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace Infinite.Shaders
{
    [DataContract]public partial class GameParameters : ShaderMixinParameters
    {
        public static readonly PermutationParameterKey<bool> EnableColorEffect = ParameterKeys.NewPermutation<bool>(false);
    };
    internal static partial class ShaderMixins
    {
        internal partial class InfiniteEffectMain  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "XenkoForwardShadingEffect");
                if (context.GetParam(GameParameters.EnableColorEffect))
                    context.Mixin(mixin, "SimpleColorEffect");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("InfiniteEffectMain", new InfiniteEffectMain());
            }
        }
    }
}
